# Generated by Django 5.1.4 on 2025-03-03 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_derniere_connexion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.customuser',),
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.customuser',),
        ),
        migrations.CreateModel(
            name='Clientadditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_livraison', models.TextField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('pays', models.CharField(blank=True, max_length=100, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Vendeuradditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(max_length=100, unique=True)),
                ('description_boutique', models.TextField(blank=True, null=True)),
                ('logo_boutique', models.ImageField(blank=True, null=True, upload_to='boutiques/logos/')),
                ('statut_validation', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=15)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('numero_rci', models.CharField(blank=True, max_length=50, null=True)),
                ('certificat_activite', models.FileField(blank=True, null=True, upload_to='boutiques/documents/')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendeur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendeur',
                'verbose_name_plural': 'Vendeurs',
            },
        ),
    ]
