# Generated by Django 5.1.4 on 2025-03-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_is_email_verified_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendeuradditional',
            name='certificat_activite',
            field=models.FileField(blank=True, null=True, upload_to='media/documents/'),
        ),
        migrations.AlterField(
            model_name='vendeuradditional',
            name='logo_boutique',
            field=models.ImageField(blank=True, null=True, upload_to='media/logos/'),
        ),
    ]
