# Generated by Django 5.1.4 on 2025-03-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_emailverification_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nom',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='prenom',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
