# Generated by Django 5.1.4 on 2025-03-05 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_emailverification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('texte', 'Texte'), ('nombre', 'Nombre'), ('selection', 'Sélection')], default='texte', max_length=10)),
                ('est_filtrable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Attribut produit',
                'verbose_name_plural': 'Attributs produits',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('statut', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='api.categorie')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description_courte', models.CharField(blank=True, max_length=255, null=True)),
                ('description_complete', models.TextField()),
                ('prix_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_promo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantite_stock', models.IntegerField(default=0)),
                ('statut', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=50, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='api.categorie')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='api.vendeur')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_image', models.ImageField(upload_to='images/products')),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('est_principale', models.BooleanField(default=False)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.produit')),
            ],
            options={
                'verbose_name': 'Image produit',
                'verbose_name_plural': 'Images produits',
                'ordering': ['ordre_affichage'],
            },
        ),
        migrations.CreateModel(
            name='ValeurAttributProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=100)),
                ('attribut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attributproduit')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributs', to='api.produit')),
            ],
            options={
                'verbose_name': "Valeur d'attribut",
                'verbose_name_plural': "Valeurs d'attributs",
                'unique_together': {('produit', 'attribut')},
            },
        ),
    ]
