# Generated by Django 5.1.4 on 2025-04-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_attributproduit_categorie_produit_imageproduit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/categories'),
        ),
    ]
